### ISSUE TITLE
Python 2.7 compatibility broken

### ISSUE THREAD

**Issue by octete** [esplinr/HtmlLogger#4]
Hi,

I was trying to test this plugin in python 2.7, but I was getting exceptions like:
```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/supybot/log.py", line 361, in m
    return f(self, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/supybot/irclib.py", line 126, in __call__
    method(irc, msg)
  File "/home/ircbot/supybot/plugins/HtmlLogger/plugin.py", line 407, in doNotice
    self.doLog(irc, channel, True, None, '-%s- %s', msg.nick, text)
  File "/home/ircbot/supybot/plugins/HtmlLogger/plugin.py", line 337, in doLog
    log = self.getLog(irc, channel)
  File "/home/ircbot/supybot/plugins/HtmlLogger/plugin.py", line 305, in getLog
    with open(logPath, encoding='utf-8', mode='r'+bin_mode) as logFile:
ValueError: binary mode doesn't take an encoding argument
ERROR 2014-09-10T18:41:37 Exception id: 0x23abb
```

So, looking at the history, I saw that this was fixed in: ced60e299055d768f4fb78356d36b34a415700b5   by removing the ``encoding='utf-8``, but then, it was added again in 5554bd3d.
Any reason for that? Could I send you a PR to get that fix? (in case that's needed for python 3.x)

**Comment by esplinr** [comment]
I apologize that I let this sit for so long.

I managed to break this in 0f99b473. It was due to a misunderstanding of Valentin Lorentz's fix in ced60e2. I saw that the documentation said that the open function from io allowed an explicit encoding (explicit is better than implicit), but I didn't think it through to realize that the encoding doesn't make sense in binary mode. I should have taken the time to set up a test Python 2.7 environment before committing the change.

Thank you for pointing this out, and I am sorry that it was broken for so long.
